student_name = input("Enter your name : ")
student_age = int(input("Enter student age : "))
student_usn = input("Enter student usn : ")
student_address = (input("enter address : "))
print(f"student name is {student_name}")
print(f"student age is {student_age}")
print(f"student usn is {student_usn}")
print(f"student address is {student_address}")


teacher_name = input("Enter your teacher name : ")
teacher_subject = input("Enter teacher subject : ")
teacher_course = input("Enter teacher course : ")
print(f"teacher name is {teacher_name}")
print(f"teacher subject is {teacher_subject}")
print(f"teacher course is {teacher_course}")